function fillIframe(text,n){jQuery('#previewWidget-'+n).contents().find('body').append(text);var el=document.createElement("script");el.setAttribute("type","text/javascript");el.setAttribute("src","https://code.jquery.com/jquery-1.9.1.min.js");jQuery("#previewWidget-"+n).contents().find("body")[0].appendChild(el);el=document.createElement("script");el.setAttribute("type","text/javascript");el.appendChild(document.createTextNode('eval(document.getElementById("settings").innerHTML);'));jQuery("#previewWidget-"+n).contents().find("body")[0].appendChild(el);el=document.createElement("script");el.setAttribute("type","text/javascript");el.setAttribute("src","https://spoonacular.com/cdn/spoonacular-1.4.min.js");jQuery("#previewWidget-"+n).contents().find("body")[0].appendChild(el);jQuery('#previewWidget-'+n).ready(function(){});}
function generateIngredientVisualizer(){jQuery('#previewWidget-1').contents().find('body').html('');var text='<pre id="spoonacular-ingredients" style="display:none">\n';text+=jQuery('#ingredientArea-1').val();text+='\n</pre>\n';text+='<div id="spoonacular-ingredient-visualizer"></div>\n';text+='<script type="text/javascript">\n';text+=' var spoonacularServings = '+jQuery('#servings-1').val()+';\n';text+=' var spoonacularMeasure = \''+jQuery('input[name=measure]:checked').val()+'\';\n';text+=' var spoonacularView = \''+jQuery('input[name=view]:checked').val()+'\';\n';text+='</script>\n';var showText=text;showText+='<script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.min.js"></script>\n';showText+='<script type="text/javascript" src="https://spoonacular.com/cdn/spoonacular-1.4.min.js"></script>';jQuery('#spoonacularCode').val(showText);text=text.replace('script ','script id="settings" ');fillIframe(text,1);jQuery('#previewWidget-1').fadeIn();jQuery('#codeResult-1').fadeIn();}
function generatePriceEstimator(){jQuery('#previewWidget-2').contents().find('body').html('');var text='<pre id="spoonacular-ingredients" style="display:none">\n';text+=jQuery('#ingredientArea-2').val();text+='\n</pre>\n';text+='<div id="spoonacular-price-estimator"></div>\n';text+='<script type="text/javascript">\n';text+=' var spoonacularServings = '+jQuery('#servings-2').val()+';\n';text+=' var spoonacularPriceView = '+jQuery('input[name=pview]:checked').val()+';\n';text+='</script>\n';var showText=text;showText+='<script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.min.js"></script>\n';showText+='<script type="text/javascript" src="https://spoonacular.com/cdn/spoonacular-1.4.min.js"></script>';jQuery('#spoonacularCode').val(showText);text=text.replace('script ','script id="settings" ');fillIframe(text,2);jQuery('#previewWidget-2').fadeIn();jQuery('#codeResult-2').fadeIn();}
function generateNutritionVisualizer(){try{jQuery('#previewWidget-3').contents().find('body').html('');}catch(e){jQuery('#previewWidget-3').contents().find('body').html('');}
var text='<pre id="spoonacular-ingredients" style="display:none">\n';text+=jQuery('#ingredientArea-3').val();text+='\n</pre>\n';text+='<div id="spoonacular-nutrition-visualizer"></div>\n';text+='<script type="text/javascript">\n';text+=' var spoonacularServings = '+jQuery('#servings-3').val()+';\n';text+='</script>\n';var showText=text;showText+='<script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.min.js"></script>\n';showText+='<script type="text/javascript" src="https://spoonacular.com/cdn/spoonacular-1.4.min.js"></script>';jQuery('#spoonacularCode').val(showText);text=text.replace('script ','script id="settings" ');fillIframe(text,3);jQuery('#previewWidget-3').fadeIn();jQuery('#codeResult-3').fadeIn();}

var activeTab = 1;
function spoonacularShowTab(tabNumber) {
    // hide currently active tab
    jQuery('#tabs-container'+activeTab).slideUp(300, function () {
        jQuery('#tabs-container'+tabNumber).slideDown(300);
        jQuery('#tabHead'+activeTab).removeClass("current");
        jQuery('#tabHead'+tabNumber).addClass("current");
        activeTab = tabNumber;
    });
}